name: Build Docker Image and Retrieve Artifact

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker Image
              run: docker build -t imato:latest .

            - name: Save Docker Image ID
              id: save-image-id
              run: |
                  echo "IMAGE_ID=$(docker images -q imato:latest)" >> $GITHUB_ENV

    retrieve-artifact:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: Copy Artifact from Docker Image
              run: docker cp ${{ needs.build.outputs.image_id }}:/home/apk/artifact.txt .

            - name: Display Artifact Content
              run: cat artifact.txt
